version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo "Installing dependencies using node 18"
      - npm install

  build:
    commands:
      - echo "Building the React Project"
      - npm run build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
